---
title: "ENVS 4432 Assignment 6 Redden"
author: "Aiden Redden"
date: "2025-10-29"
output: html_document
bibliography: references.bib
---

Paper: [@Tsengetal]

## Introduction

A method for bird sound recognition that is easily accessible and time efficient is needed to help monitoring of avian species. Currently there are a select number of automatic recognizers for bird sound identification, including Merlin Bird ID or BirdNET. These recognizers are limited in the amount of audio they can correctly identify, as they must be validated by a human observer after recognition is run on audio, taking large amounts of time to validate species identifications. Tseng et al. (2025) proposes a solution to this issue using the software BirdNET from Cornell Lab of Ornithology. BirdNET is a open source recognizer used for identifying bird species from audio. The software produces a species identifcation for audio along with a confidence level from zero to one. This confidence level indicates the liklihood of an accurate prediction by BirdNET, with higher values indicating higher prediction accuracy. Confidence scores can be influenced by many factors, including species, background noise, or overlap between calls. Within BirdNET, a threshold may be set to disregard identifications below a certain confidence level, and while this may be useful for certain projects, this may remove true positives from the predictions. The confidence score accuracy will also vary between species, with some species having very low confidence scores will still have correct predictions, while others may have very high confidence levels being false positives. To solve this, creating a species-specific confidence threshold is needed to ensure true positives are kept, while false positives are ignored. The papers objectives were to compare a universal confidence threshold to a species-specific threshold, and to examine if BirdNET performance is correlated to species call complexity. They used a audio dataset consisting of 66 recording sites and focusing on 19 species with a range of song complexity and singing rates.

## Methods

##### Study Area

The data was collected in British Columbia, Canada, in 66 sites selected to include a diverse range of forest stands. Each site was located at least two kilometers away from each other to account for the autonomous recording units detection range. One AudioMoth was placed on each site during the breeding season from May - July in 2020 and 2021. The units recorded audio from 4 am to 7 am daily to conincide with peak vocal activity for songbirds. Each unit recorded for a minute and then had four minutes downtime, repeated for the three hour recording period. 36 one minute recordings were collected for each day, per site.

##### Audio processing 

Data was then run through BirdNET Lite. Default settings for BirdNET analysis were used.

##### Target Species 

They selected 19 species with ranging song complexities and singing rates. Multiple metrics were used to compare song complexity.

##### Validation 

Stratified sampling for 0.05 confidence score classes were used for the validation, with bins from 0.1 - 0.15 up to 0.95-1 confidence score. Ten recordings were selected for each bin, resulting in 180 recordings per species. Human observes then validated the species identification, noting true positive or false positive.

##### Calibration curve 

Once validation was complete, a generalized linear model with a binomial distribution was used with the confidence score as the predictor variable and true or false positive as the response variable.

##### Confidence threshold

Two approaches were used for the confidence thresholds. One approach, which is the general confidence threshold of 0.7. The other approach, a species-specific confidence threshold for a minimum precision of 0.9 for species identification.

## Results

##### Confidence rate and true positives 

They found a positive relationship between confidence score and true positive between all species. Some species saw high true positive rates even with low confidence level, such as Myrtle Warbler (*Setophaga coronata*). Some groups seen a gradual increase in true positive rate in relation to confidence, indicating high levels of confidence are needed to predict the species. Other groups were between these two extremes.

![Fig. 1 Calibration curves for the 19 target species. Compares true positive rate to BirdNET confidence score. This was based on a logistic regression with true positive or false positive as the response variables, with BirdNET confidence as predictor. This was then back-transformed to get the true positive rate. Retrieved from Tseng et al. (2025) figure 4. ](images/Figure 4 Tseng et al.png)

##### Confidence threshold setting

With the default 0.7 threshold, they found a high precision from 0.7 to 1.0. This universal threshold resulted in only 17 percent (14% SE) of BirdNET predictions being kept. Using the species-specific threshold resulted in a precision higher than 0.9. This also retained more predictions, 70 percent (37% SE). Most species had thresholds set lower than 0.35, with only two species, Brown Creeper (*Certhia americana*) and Varied Thrush *(Ixoreus naevius*) needing 0.95 as the confidence threshold.

## Discussion

##### BirdNET performance and thresholds

The paper found setting species-specific thresholds to be the best option for precision and retaining BirdNET predictions. They suggest setting these thresholds for future use of BirdNET. They also suggest that manually setting thresholds for each project, as the species-specific thresholds calculated by them will differ from other projects due to recording equipment, species composition, and environmental noise and conditions.

They also found no relationship between call complexity and BirdNET performance, indicating BirdNET may not be better to detect more species with high song complexity. This conclusion is limited due to the few species they targeted, and examining more species would be beneficial.

They found that the misidentifications were mostly due to overlapping features in calls between species, such as similar frequency and tone between species.

The paper did complete their objectives, both comparing and determining that species-specific thresholds were more accurate, and that BirdNET performance was not correlated to song complexity.

## References
